### ISSUE TITLE
Elaphaea Users Custom Database Properties, Functions, and Lambas

### ISSUE THREAD

**Issue by strawhat19** [Piratechs-LLC/Elaphaea#11]
- [x] Tokens
- [x] Bacon Points
- [x] Token Purchases
- [x] Bacon Purchases
- [x] Bacon Level // Tier
- [x] Overall Points // Score?
- [x] Custom Character Design Upload
